name:                triskadekaphilia
version:             0.1.0.0
github:              "nomicflux/triskadekaphilia"
license:             BSD3
author:              "M Anderson"
maintainer:          "nomicflux@gmail.com"
copyright:           "2019 M Anderson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/triskadekaphilia#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - synthesizer-core
  - pipes
  - pipes-concurrency
  - gloss
  - stm
  - unordered-containers
  - hashable

executables:
  triskadekaphilia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - pipes
    - pipes-concurrency
    - gloss
    - triskadekaphilia

tests:
  triskadekaphilia-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - triskadekaphilia
